In [15]:
import numpy as np
arr = np.arange(71,80)
arr

array([71, 72, 73, 74, 75, 76, 77, 78, 79])

In [17]:
arr + 1

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [18]:
1/arr

array([0.01408451, 0.01388889, 0.01369863, 0.01351351, 0.01333333,
       0.01315789, 0.01298701, 0.01282051, 0.01265823])

In [19]:
arr*arr

array([5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241])

In [20]:
arr_2d=arr.reshape(3,3)
arr_2d

array([[71, 72, 73],
       [74, 75, 76],
       [77, 78, 79]])

In [21]:
arr_2d**2

array([[5041, 5184, 5329],
       [5476, 5625, 5776],
       [5929, 6084, 6241]], dtype=int32)

In [22]:
arr_1d = np.array([1,2,3])
arr_2d*arr_1d

array([[ 71, 144, 219],
       [ 74, 150, 228],
       [ 77, 156, 237]])

In [23]:
arr_2d / arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.sqrt(arr)

array([8.42614977, 8.48528137, 8.54400375, 8.60232527, 8.66025404,
       8.71779789, 8.77496439, 8.83176087, 8.88819442])

In [25]:
np.exp(arr)

array([6.83767123e+30, 1.85867175e+31, 5.05239363e+31, 1.37338298e+32,
       3.73324200e+32, 1.01480039e+33, 2.75851345e+33, 7.49841700e+33,
       2.03828107e+34])

In [26]:
np.sin(arr_2d)

array([[ 0.95105465,  0.25382336, -0.67677196],
       [-0.98514626, -0.38778164,  0.56610764],
       [ 0.99952016,  0.51397846, -0.44411267]])

In [27]:
np.log(arr_2d)

array([[4.26267988, 4.27666612, 4.29045944],
       [4.30406509, 4.31748811, 4.33073334],
       [4.34380542, 4.35670883, 4.36944785]])

In [28]:
np.insert(arr,7,55)

array([71, 72, 73, 74, 75, 76, 77, 55, 78, 79])

In [30]:
np.delete(arr,6)

array([71, 72, 73, 74, 75, 76, 78, 79])

In [31]:
np.append(arr,88)

array([71, 72, 73, 74, 75, 76, 77, 78, 79, 88])

In [32]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [34]:
np.concatenate((a,b),axis = None)

array([1, 2, 3, 4, 5, 6])

In [36]:
np.where(arr>74,0,arr)

array([71, 72, 73, 74,  0,  0,  0,  0,  0])

In [37]:
np.where(arr<74,0,arr)

array([ 0,  0,  0, 74, 75, 76, 77, 78, 79])

In [38]:
np.where(arr>75,1,0)

array([0, 0, 0, 0, 0, 1, 1, 1, 1])

In [39]:
np.where(arr_2d <= 75,0,arr_2d)

array([[ 0,  0,  0],
       [ 0,  0, 76],
       [77, 78, 79]])